on: 
  push: 
    branches: 
    - main
jobs:
  deploy_website:
    name: Deploy ASBerezkin Website
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install deps
        run: npm ci
      - name: Build Project
        run: npm run build
